### ISSUE TITLE
rails-create-action-readme

### ISSUE THREAD

**Issue by ejeffries1** [learn-co-curriculum/rails-create-action-readme#24]
### Canvas Link

https://learning.flatironschool.com/courses/1881/assignments/125519?module_item_id=259387

### Concern

I did not like the lesson, the directions on the lesson weren't clear and, I believe one thing was said and you meant something else. The directions I tried didn't fix the errors. I'm not sure whats going on with the rails lessons but these are not working correctly along with the lessons being unclear.

### Additional Context

 def create
    post = Post.new
    post.title = params[:title]
    post.description = params[:description]
    post.save
    redirect_to post_path(post)
  end

Issues such as this. In the lesson you stated to put @post inside the post_path, which brought up the error instead of passing it. I had to actually change it to post.

**Comment by ihollander** [comment]
Hi @ejeffries1 - thanks for your feedback and sorry the lesson instructions weren't clear. We'll make some updates to make it the steps required to code along with this lesson more explicit.

In regards to the specific code you mentioned, the code for the `create` action will work if you either use an instance variable for `@post` or a local variable `post`, so long as you use the same type of variable consistently in that method. We show using the instance variable since that is a convention among Rails developers when writing controller actions, and for actions that render a view, instance variables are required. This is what the completed code for the controller should look like:

```rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:title]
    @post.description = params[:description]
    @post.save
    redirect_to post_path(@post)
  end
end
```
